Add active and inactive courses table
Brightspace/insights-engagement-dashboard pull request #203
Opened 2020-12-10 00:38 UTC by rohitvinnakota

2020-12-14 09:11 UTC, MykolaGalian requested changes

2020-12-14 09:11 UTC, MykolaGalian commented on components/user-drill-courses-table.js
> +			isStudentSuccessSys: { type: Boolean, attribute: false }
Please return functionality from "Add predicted grade" PR https://github.com/Brightspace/insights-engagement-dashboard/pull/186 according to story [US122292](https://rally1.rallydev.com/#/23525809118d/iterationstatus?detail=%2Fuserstory%2F454991118320&fdp=true?fdp=true): [Engagement][UserDrill] Add predicted grade

2020-12-14 12:55 UTC, MykolaGalian commented on components/user-drill-courses-table.js
> +			? formatDateTime(new Date(user[ACTIVE_TABLE_COURSES.COURSE_LAST_ACCESS]), { format: 'medium' })
Need to add logic for inactive table `INACTIVE_TABLE_COURSES.COURSE_LAST_ACCESS`, since the active and inactive table has a different number of columns

2020-12-14 15:05 UTC, johngwilkinson commented on components/user-drill-courses-table.js
> +		} else {
The inactive columns are identical to the active with one removed, right? I'd be inclined to define the columns just once then `splice()` out the one you don't need. Same could be said above in the preprocess and format data methods.

```
const columns = [...];
if(this.isInactiveTable) columns.splice(2, 1); // I think - might be off by one
return columns;
```

2020-12-14 15:05 UTC, johngwilkinson commented on components/user-drill-view.js
> +					.user="${this.user}"
nit: although it's not necessary, it might help the reader to include `.isActiveTable=${Boolean(false)}`

2020-12-14 19:10 UTC, johngwilkinson approved these changes

2020-12-14 19:10 UTC, johngwilkinson commented on components/user-drill-courses-table.js
> +	_formatDataForDisplay(user) {
just noticed: this doesn't take a `user`, it takes a `course`

2020-12-14 19:10 UTC, johngwilkinson commented on components/user-drill-courses-table.js
> +				user[ACTIVE_TABLE_COLUMNS.CURRENT_GRADE] ? formatPercent(user[ACTIVE_TABLE_COLUMNS.CURRENT_GRADE] / 100, numberFormatOptions) : '',
Personally, I think it would be nice not to repeat this formatting here and below by using splice, but I'm okay with it.

2020-12-14 20:47 UTC, MykolaGalian approved these changes

2020-12-14 20:47 UTC, MykolaGalian commented
unit tests?

2020-12-14 20:49 UTC, bemailloux commented
> unit tests?

I'm working on these. We might merge the PR without them so the rest of the work for Milestone 4 can proceed

2020-12-14 20:55 UTC, MykolaGalian commented on components/user-drill-courses-table.js
> +		if (this.skeleton) {
please add logic for the case when there is no predicted grade column

2020-12-15 15:00 UTC, NicholasHallman approved these changes

2020-12-15 16:30 UTC, merged

2020-12-15 16:31 UTC, johngwilkinson commented on components/user-drill-courses-table.js
> +		return this.data._data;
`data._data` is private; can you pass `orgUnitTree` to this class as a property instead?

2020-12-15 16:43 UTC, bemailloux commented on components/user-drill-courses-table.js
> +		return this.data._data;
Addressed in #213